// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 增
type OrderAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         uint32                 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	OrderSn       int64                  `protobuf:"varint,4,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAddReq) Reset() {
	*x = OrderAddReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAddReq) ProtoMessage() {}

func (x *OrderAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAddReq.ProtoReflect.Descriptor instead.
func (*OrderAddReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *OrderAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderAddReq) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderAddReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *OrderAddReq) GetOrderSn() int64 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

type OrderAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAddResp) Reset() {
	*x = OrderAddResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAddResp) ProtoMessage() {}

func (x *OrderAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAddResp.ProtoReflect.Descriptor instead.
func (*OrderAddResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *OrderAddResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderAddResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 删
type OrderDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       int64                  `protobuf:"varint,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeleteReq) Reset() {
	*x = OrderDeleteReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeleteReq) ProtoMessage() {}

func (x *OrderDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeleteReq.ProtoReflect.Descriptor instead.
func (*OrderDeleteReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDeleteReq) GetOrderSn() int64 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

type OrderDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeleteResp) Reset() {
	*x = OrderDeleteResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeleteResp) ProtoMessage() {}

func (x *OrderDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeleteResp.ProtoReflect.Descriptor instead.
func (*OrderDeleteResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *OrderDeleteResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderDeleteResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 改
type OrderUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       int64                  `protobuf:"varint,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         uint32                 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdateReq) Reset() {
	*x = OrderUpdateReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateReq) ProtoMessage() {}

func (x *OrderUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateReq.ProtoReflect.Descriptor instead.
func (*OrderUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *OrderUpdateReq) GetOrderSn() int64 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

func (x *OrderUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderUpdateReq) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderUpdateReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type OrderUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdateResp) Reset() {
	*x = OrderUpdateResp{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateResp) ProtoMessage() {}

func (x *OrderUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateResp.ProtoReflect.Descriptor instead.
func (*OrderUpdateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *OrderUpdateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderUpdateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 查 - 单个
type OrderGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       int64                  `protobuf:"varint,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGetReq) Reset() {
	*x = OrderGetReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGetReq) ProtoMessage() {}

func (x *OrderGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGetReq.ProtoReflect.Descriptor instead.
func (*OrderGetReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *OrderGetReq) GetOrderSn() int64 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

type OrderGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         uint32                 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,5,opt,name=num,proto3" json:"num,omitempty"`
	OrderSn       int64                  `protobuf:"varint,6,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGetResp) Reset() {
	*x = OrderGetResp{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGetResp) ProtoMessage() {}

func (x *OrderGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGetResp.ProtoReflect.Descriptor instead.
func (*OrderGetResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *OrderGetResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderGetResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderGetResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderGetResp) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderGetResp) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *OrderGetResp) GetOrderSn() int64 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

// 查 - 列表
type OrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListReq) Reset() {
	*x = OrderListReq{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListReq) ProtoMessage() {}

func (x *OrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListReq.ProtoReflect.Descriptor instead.
func (*OrderListReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *OrderListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*OrderInfo           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResp) Reset() {
	*x = OrderListResp{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResp) ProtoMessage() {}

func (x *OrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResp.ProtoReflect.Descriptor instead.
func (*OrderListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *OrderListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderListResp) GetData() []*OrderInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OrderListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         uint32                 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	OrderSn       int64                  `protobuf:"varint,4,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *OrderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderInfo) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfo) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *OrderInfo) GetOrderSn() int64 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05proto\"c\n" +
	"\vOrderAddReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\aR\x05price\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\x12\x18\n" +
	"\aorderSn\x18\x04 \x01(\x03R\aorderSn\"4\n" +
	"\fOrderAddResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\"*\n" +
	"\x0eOrderDeleteReq\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\x03R\aorderSn\"7\n" +
	"\x0fOrderDeleteResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\"f\n" +
	"\x0eOrderUpdateReq\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\x03R\aorderSn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\aR\x05price\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x03R\x03num\"7\n" +
	"\x0fOrderUpdateResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\"'\n" +
	"\vOrderGetReq\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\x03R\aorderSn\"\x8a\x01\n" +
	"\fOrderGetResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\aR\x05price\x12\x10\n" +
	"\x03num\x18\x05 \x01(\x03R\x03num\x12\x18\n" +
	"\aorderSn\x18\x06 \x01(\x03R\aorderSn\">\n" +
	"\fOrderListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"q\n" +
	"\rOrderListResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12$\n" +
	"\x04data\x18\x03 \x03(\v2\x10.proto.OrderInfoR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"a\n" +
	"\tOrderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\aR\x05price\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\x12\x18\n" +
	"\aorderSn\x18\x04 \x01(\x03R\aorderSn2\xa5\x02\n" +
	"\x05Order\x123\n" +
	"\bOrderAdd\x12\x12.proto.OrderAddReq\x1a\x13.proto.OrderAddResp\x12<\n" +
	"\vOrderDelete\x12\x15.proto.OrderDeleteReq\x1a\x16.proto.OrderDeleteResp\x12<\n" +
	"\vOrderUpdate\x12\x15.proto.OrderUpdateReq\x1a\x16.proto.OrderUpdateResp\x123\n" +
	"\bOrderGet\x12\x12.proto.OrderGetReq\x1a\x13.proto.OrderGetResp\x126\n" +
	"\tOrderList\x12\x13.proto.OrderListReq\x1a\x14.proto.OrderListRespB\x04Z\x02./b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_proto_goTypes = []any{
	(*OrderAddReq)(nil),     // 0: proto.OrderAddReq
	(*OrderAddResp)(nil),    // 1: proto.OrderAddResp
	(*OrderDeleteReq)(nil),  // 2: proto.OrderDeleteReq
	(*OrderDeleteResp)(nil), // 3: proto.OrderDeleteResp
	(*OrderUpdateReq)(nil),  // 4: proto.OrderUpdateReq
	(*OrderUpdateResp)(nil), // 5: proto.OrderUpdateResp
	(*OrderGetReq)(nil),     // 6: proto.OrderGetReq
	(*OrderGetResp)(nil),    // 7: proto.OrderGetResp
	(*OrderListReq)(nil),    // 8: proto.OrderListReq
	(*OrderListResp)(nil),   // 9: proto.OrderListResp
	(*OrderInfo)(nil),       // 10: proto.OrderInfo
}
var file_user_proto_depIdxs = []int32{
	10, // 0: proto.OrderListResp.data:type_name -> proto.OrderInfo
	0,  // 1: proto.Order.OrderAdd:input_type -> proto.OrderAddReq
	2,  // 2: proto.Order.OrderDelete:input_type -> proto.OrderDeleteReq
	4,  // 3: proto.Order.OrderUpdate:input_type -> proto.OrderUpdateReq
	6,  // 4: proto.Order.OrderGet:input_type -> proto.OrderGetReq
	8,  // 5: proto.Order.OrderList:input_type -> proto.OrderListReq
	1,  // 6: proto.Order.OrderAdd:output_type -> proto.OrderAddResp
	3,  // 7: proto.Order.OrderDelete:output_type -> proto.OrderDeleteResp
	5,  // 8: proto.Order.OrderUpdate:output_type -> proto.OrderUpdateResp
	7,  // 9: proto.Order.OrderGet:output_type -> proto.OrderGetResp
	9,  // 10: proto.Order.OrderList:output_type -> proto.OrderListResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
